### ISSUE TITLE
Alternative ways to cycle through alternate ini files

### ISSUE THREAD

**Issue by bootsector** [MiSTer-devel/Template_MiSTer#31]
Being able to cycle through alternate ini files by using IO board buttons combination would be great. Only current way is via a joystick. Not even a keyboard is supported, unfortunately.

**Comment by ludzeller** [comment]
+1!

**Comment by sorgelig** [comment]
Keyboard is supported. Probably something wrong with your keyboard.

**Comment by bootsector** [comment]
This has been implemented inside the framework, inside the menu that shows the screen resolution. Closing.

**Comment by ludzeller** [comment]
The problem is that you need to have a working monitor with the current implementations.

But it is common to switch between various display setups, e.g. 15khz and higher resolutions, especially if only using Direct Video via HDMI to VGA, RGB, etc. adapters.

When switching between these output devices it would be super helpful to be able to switch to the correct ini file in order to actually see something on the screen and not having to rely on another computer to edit the ini.

Please reopen the ticket.

**Comment by bootsector** [comment]
Agree! Reopening!

**Comment by sorgelig** [comment]
i will think about possible solution

**Comment by birdybro** [comment]
Probably a combination not dissimilar from the current controller combination.

Menu + Arrow keys.

Hold F12 and press Right/Left/Up/Down for Default/Alt1/Alt2/Alt3 ini files.

**Comment by ludzeller** [comment]
> Probably a combination not dissimilar from the current controller combination would be good.
> 
> Menu + Arrow keys.
> 
> While OSD is open, hold F12 and press Right/Left/Up/Down for Default/Alt1/Alt2/Alt3 ini files.

That would again require a monitor and a controller.

Ideally you could change ini just with the MiSter itself, but given the limited amount of buttons that might be difficult. Personally I would be happy able to switch to only one or two alt files. E.g. by holding OSD for Alt1 or User during reboot. 

A compromise for being able to alternate more ini files would be holding OSD or User during reboot while also holding arrow keys on the controller as you describe.

**Comment by sorgelig** [comment]
I'm thinking of this way:
You need to make main ini file as fail safe while using alt inis for potentially not safe configs.
Then i can add a check for I/O button "OSD" on booting to switch to main INI file if it held down. 

It's unsafe and inconvenient to use controller buttons combinations as it may be triggered unintentionally by unaware user. And it's in general is a bad behavior.

**Comment by ludzeller** [comment]
> I'm thinking of this way: You need to make main ini file as fail safe while using alt inis for potentially not safe configs. Then i can add a check for I/O button "OSD" on booting to switch to main INI file if it held down.
> 
> It's unsafe and inconvenient to use controller buttons combinations as it may be triggered unintentionally by user who is unaware of such feature. And it's in general is a bad behavior.

I like it!

Switching to main ini if 'OSD' is pressed on booting... Was just wondering if it could be only for the current boot ... That way a user with a VGA and 15KHz setup could easily switch between alt1 and main, setting alt1 as permanent ini and jumping to main ini only if necessary. 

That would also double as a safe mode option for failed configs in general.

**Comment by birdybro** [comment]
> > Probably a combination not dissimilar from the current controller combination would be good.
> > Menu + Arrow keys.
> > While OSD is open, hold F12 and press Right/Left/Up/Down for Default/Alt1/Alt2/Alt3 ini files.
> 
> That would again require a monitor and a controller.

No. It would just require a keyboard.

F12 + Right/Left/Up/Down

**Comment by sorgelig** [comment]
Generally speaking, the method i wrote above is already working but instead of OSD button you just need to powercycle the MiSTer. After power cycle main INI will be used.

**Comment by ludzeller** [comment]
Good to know! 

But that way I will need a monitor and input device in order to change back to the alternative ini. So probably not 100% what we are looking for here.

**Comment by ludzeller** [comment]
> MiSTer without input device is useless, isn't? :)

Can still run Attract mode! :D

But sure, usually there is an input device. 

Not having to rely on an input device would be for those troubled cases where everything fails and where you want to have a no dependencies recovery mode.

**Comment by sorgelig** [comment]
Ok. in latest commit i've added ini selection.
You have to hold OSD button on I/O board while menu loading. Basically you press OSD menu and then reset key. Wait for DISK LED to become always ON. Then use dpad or cursor key to select. ESC to stay in main INI.

**Comment by ludzeller** [comment]
Sounds good! Can we pull it via update_all.sh or should we pull it manually? Have you pushed that commit already?

**Comment by sorgelig** [comment]
It's in Main. Already pushed commits but not released yet. Should be available in unstable builds.

**Comment by ludzeller** [comment]
Are these the unstable builds you are referring to?
https://github.com/MiSTer-devel/Main_MiSTer/tree/master/releases

If so, can I install them via update_all.sh or is there some other procedure that is documented somewhere maybe? Thank you.

**Comment by ludzeller** [comment]
Finally had the time to pull your release via update_all.sh and test it.

Works well for my setup, thank you!
