### ISSUE TITLE
Video info sometimes shows the wrong original resolution

### ISSUE THREAD

**Issue by dfilskov** [MiSTer-devel/Template_MiSTer#32]
This happens e.g. in MINIMIG I think. Also GAUNT2's original resolution is shown as 336:240 but actually it's using 448:256

I've tested this by tuning vscale_border and custom aspect ratios to make the signal match the pixels on my flatpanel.

In GAUNT2 at integers of 448 and 256 (AR 1.75) it matches the pixels exactly/perfectly (all pixels become even) but the video info says it should be integers of 336 and 240 (AR 1.5 which doesn't create integer scaling).

Screenshots are saved as 336x240 though so why must the output be scaled up using integers of 448x256? Quite confusing :)

Minimig some screenshots are saved as 1024x256 or so even though that's not what it's using on the flat panel.

I tested this by using integer scaling and found the perfect scaling for both Gauntlet 1 and Gauntlet 2 - they both have the same video info and screenshot size 336x240 but to make them become perfect integer scaling they need to be treated as 448x256.

**Comment by sorgelig** [comment]
Don't count Minimig. It's very specific core and it's a problem to make it correct due to different factors.
As for other cores - it should be problem of specific core and need to be reported in appropriate core (not here).

**Comment by dfilskov** [comment]
I see. Thanks! - We should let the Gauntlet core developer know then.

**Comment by dfilskov** [comment]
It was my mistake sorry!!

For GAUNTLET - to get integer scaling - I had added this to the MiSTer.ini by mistake:

 [GAUNTLET] ; 336:256 (video info says 240)
video_mode=1920,16,8,16,1920,16,8,16,230500
vscale_border=120
custom_aspect_ratio_1=1792:1280
custom_aspect_ratio_2=1792:1536

... but it should have been

[GAUNTLET] ; 336:240
video_mode=1920,16,8,16,1920,16,8,16,230500
vscale_border=120
custom_aspect_ratio_1=1680:1200
custom_aspect_ratio_2=1680:1440 ; too tall

or simply

[GAUNTLET] ; 336:240
vscale_border=120
custom_aspect_ratio_1=1680:1200

(my display is square: 1920x1920 but set to 1920x1440 as standard in MiSTer.ini)

Sorry for the confusion!
