### ISSUE TITLE
Latest commit won't compile in Quartus 17.0.0

### ISSUE THREAD

**Issue by birdybro** [MiSTer-devel/Template_MiSTer#34]
![image](https://user-images.githubusercontent.com/16388068/120208983-5c99f100-c1eb-11eb-90d0-2f15c4a114ce.png)

Using the previous commit files works.

Not sure if this is expected or not, but I noticed it the other day.

**Comment by sorgelig** [comment]
fixed

**Comment by paulb-nl** [comment]
It seems you pushed to the wrong repo (Main).

**Comment by sorgelig** [comment]
lol
