### ISSUE TITLE
Bug in the framework showing up only when using "Switch to USB"

### ISSUE THREAD

**Issue by jca2021** [MiSTer-devel/Template_MiSTer#36]
The core menus look for MISTer.ini in /media/usb0, not /media/fat.
This leads to grayed items in the menu: Cheats, items related to Saves, items related to Vertical Crop and may be others.
Temporary solution: copy MISTer.ini to /media/usb0.

**Comment by jca2021** [comment]
I spoke too early, copying MISTer.ini fixes only the items related to Vertical Crop. Although at one time I saw the other items reappear in the Genesis core they are now grayed out. I checked  other cores and only the items related to Vertical Crop are enabled. I tried to copy cheats, saves, savestates and Gamma to the SD card this did not fix the problem. I copied Gamma as the GameBoy core has the GBC Colors item grayed out. It looks like when "Switched to USB" the framework does not know where these directories are located.

**Comment by sorgelig** [comment]
It has nothing to do with template. It's HPS (Main) feature.
Actually switch to USB is kind of obsolete option, you may use symlinks from specific folder to USB and use both locations without hard switch.

Closing as issue unrelated to Template.
