### ISSUE TITLE
arcade_video: support for rotation of 24bpp images

### ISSUE THREAD

**Issue by jotego** [MiSTer-devel/Template_MiSTer#4]
Currently the arcade_video module only supports 24bpp images nominally, as in practice it will fail when compiling with a lack of BRAM error. The reason is that the rotator module needs more BRAM than available for 24bpp images (even when resolution is low such as 384x224).

**Comment by sorgelig** [comment]
if you will set no_rotate(1), i.e. constant 1, then Quartus will eliminate rotator module and it won't occupy any resources.

**Comment by jotego** [comment]
That's right. I'm using a different solution for when I need rotation in 24bpp at the moment but I wanted to leave the issue written down so we can come back to it when we have time.

**Comment by sorgelig** [comment]
ideally, rotator using DDR3 would be good.

**Comment by sorgelig** [comment]
Yes. It supports rotation of 24bit of VGA resolution (~640x480).

**Comment by sorgelig** [comment]
implemented already
