### ISSUE TITLE
Unusual synchronizer

### ISSUE THREAD

**Issue by jotego** [MiSTer-devel/Template_MiSTer#41]
Pardon my ignorance, but I have always seen synchronizers done in a blind way. This one seems to hold the signal until two samples are equal. Is there any theory behind this?

https://github.com/MiSTer-devel/Template_MiSTer/blob/1e0b938be97c855ee5a3eb6a3327c91bd84c9be4/sys/audio_out.v#L149

**Comment by sorgelig** [comment]
Yes. without it, you will hear occasional static noise in some sounds.

**Comment by jotego** [comment]
I see, thank you

**Comment by sorgelig** [comment]
inferred synchronizers aren't always work as expected. From my experience, if i want to transfer a vector (not just 1 bit) between clocks and there is enough time to get 2 samples then it's better to use this method than relay on decision of synthesizer.
