### ISSUE TITLE
Erroneous 0x00 leads my ROM build.

### ISSUE THREAD

**Issue by ZPaul2Fresh8** [MiSTer-devel/Template_MiSTer#69]
Not sure why, but after interleaving the ROM is built with an 0x0 byte. Deleting said byte leaves the ROM as desired.

**Comment by jotego** [comment]
This repository does not have anything to do with ROM interleaving etc. but maybe we can redirect you to the right forum if you give a bit more information about what you are trying to do.

**Comment by ZPaul2Fresh8** [comment]
Sorry, I don't know how it got posted here, was suppose to be in mra-tools!

**Comment by birdybro** [comment]
This issue can be closed.
