### ISSUE TITLE
DAC board (PCM5102) no sound in some cores

### ISSUE THREAD

**Issue by mills32** [MiSTer-devel/Template_MiSTer#82]
I connected a little DAC board (PCM5102) like this:

-GPIO1 PIN 2: BCK
-GPIO1 PIN 7: DIN
-GPIO1 PIN 8: LCK
-VIN: can be 3.3v or 5v, it does not matter.
-GND: any GND available
-The big switch near the ethernet port is ON (I guess SW[0]?).

On some cores (SNES, MegaDrive, ao486, Minimig, SMS, Nes, Neo-Geo, menu with BGM script) audio through GPIO1 is completely off. 

I found a change in sys_top which causes the issue:

This is from a working core (for example Gameboy):
`
	assign AUDIO_SPDIF = SW[3] ? 1'bZ : SW[0] ? HDMI_LRCLK : spdif;
`
`
	assign AUDIO_R     = SW[3] ? 1'bZ : SW[0] ? HDMI_I2S   : analog_r;
`
`
	assign AUDIO_L     = SW[3] ? 1'bZ : SW[0] ? HDMI_SCLK  : analog_l;
`

This is from a non working core (Megadrive):
`
	assign AUDIO_SPDIF = av_dis ? 1'bZ : (SW[0] | mcp_en) ? HDMI_LRCLK : spdif;
`
`
	assign AUDIO_R     = av_dis ? 1'bZ : (SW[0] | mcp_en) ? HDMI_I2S   : analog_r;
`
`
	assign AUDIO_L     = av_dis ? 1'bZ : (SW[0] | mcp_en) ? HDMI_SCLK  : analog_l;
`

I replaced this part in Megadrive core, then compiled it, and sound worked fine. 

Maybe it is not an issue at all, and I forgot to configure something else on .ini files, I don't know.

Thanks.

**Comment by sorgelig** [comment]
Yes, you forgot to ground VGA_EN pin.

**Comment by mills32** [comment]
> Yes, you forgot to ground VGA_EN pin.

Thanks a lot, everything working.
